# -*- mode: ruby -
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'
  config.vm.define "machine1" do |machine1|
    config.vm.box = "debian/bullseye64"
    machine1.vm.network "private_network", ip: "192.168.141.2"
  end
  
  config.vm.define "machine2" do |machine2|
    config.vm.box = "debian/bullseye64"
    machine2.vm.network "private_network", ip: "192.168.141.3"
  end
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 2
    vb.memory = "2048"
  end
 
  config.vm.provision "file", 
    source: "fileprov.txt",
	destination: "fileprov.txt"
	
  config.vm.synced_folder "./testdir", "/home/testdir", 
    type: "virtualbox", SharedFoldersEnableSymlinksCreate: false
  #   apt-get update
  #   apt-get install -y apache2
end
