# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

# Официальный Vagrant Cloud заблокирован, берём образы через зеркало
ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/bullseye64"

  (1..4).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}"

      node.vm.network "private_network", ip: "192.168.56.1#{i}" # Host-only сеть IP 11–14

      node.vm.synced_folder ".", "/home/vagrant/shared", type: "rsync"

      node.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y htop
      SHELL

      node.vm.provider "virtualbox" do |vb|
        vb.memory = "1024" # 2048
      end
    end
  end
end